# Generated by Django 4.2 on 2024-05-29 23:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_invoice_product_cost_product_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(help_text='Stock debe estar en 0 y 10000 unidades', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock'),
        ),
    ]
